Repository yalla-coop/earwig, pull requests merged in 2019-11, with the labels that each got.

#742 replace work period with last use of the org
  client/src/Components/Common/AntdComponents/AntdComponents.style.js
  client/src/Components/Common/AntdComponents/DatePicker.js
  client/src/Components/Common/Icon/Calendar.js
  client/src/Components/Common/Icon/Icon.js
  client/src/Components/Pages/Admin/Reviews/SingleReview.js
  client/src/Components/Pages/Review/Question/Options/DateRange.js
  client/src/Components/Pages/Review/Question/Options/Rate.js
  client/src/Components/Pages/Review/index.js
  client/src/Components/Pages/Review/validationSchema.js
  server/__test__/api/admin/reviews.getAllReviewsCSV.js
  server/__test__/database/queries/reviews.allReviewsIncAs.js
  server/__test__/database/schema/review.js
  server/controllers/admin/getAllReviewsCSV.js
  server/controllers/review.js
  server/database/dummyData/reviews.js
  server/database/models/Review.js
  server/database/queries/review.js
  server/database/queries/reviews/allReviewsIncAnswers.js
  server/middlewares/validation.js
Labels: awaiting-review

#743 Change the number of points workers can give/earn
  client/src/Components/Common/HelpfulBubble/index.js
  client/src/Components/Common/Icon/Close.js
  client/src/Components/Common/Icon/Icon.js
  client/src/Components/Common/Icon/Reply.js
  client/src/Components/Common/Navbar/Menu.js
  client/src/Components/Pages/InviteWorkers/index.js
  client/src/Components/Pages/InviteWorkers/inviteWorkers.style.js
  client/src/Components/Pages/Profile/OverallReview.js
  client/src/Components/Pages/Profile/Profile.style.js
  client/src/assets/close-icon.svg
  server/__test__/api/admin/verifyUser.js
  server/__test__/api/updateOverallHelpfulPoints.js
  server/constants.js
  server/controllers/updateHelpfulPoints.js
  server/database/queries/user/updateUserHelpfulPoints.js
Labels: awaiting-review

#746 Common design
  client/src/App.css
  client/src/App.js
  client/src/Components/Common/Button.js
  client/src/Components/Common/CancelNavbar.js
  client/src/Components/Common/CommentSection/index.js
  client/src/Components/Common/Formik/Formik.style.js
  client/src/Components/Common/Icon/Icon.js
  client/src/Components/Common/Icon/Info.js
  client/src/Components/Common/Icon/Logo.js
  client/src/Components/Common/Icon/Warning.js
  client/src/Components/Common/Link.js
  client/src/Components/Common/Navbar/Menu.js
  client/src/Components/Common/Navbar/Menu.style.js
  client/src/Components/Common/Navbar/Navbar.style.js
  client/src/Components/Common/Navbar/index.js
  client/src/Components/Common/Popover/Popover.style.js
  client/src/Components/Common/Popover/index.js
  client/src/Components/Common/StaticPages.style.js
  client/src/Components/Pages/Admin/Admin.style.js
  client/src/Components/Pages/DeleteProfile/DeleteProfile.style.js
  client/src/Components/Pages/DeleteProfile/index.js
  client/src/Components/Pages/EditProfile/EditProfile.style.js
  client/src/Components/Pages/EditProfile/EditProfileSection.js
  client/src/Components/Pages/Intro/index.js
  client/src/Components/Pages/InviteWorkers/inviteWorkers.style.js
  client/src/Components/Pages/Landing/index.js
  client/src/Components/Pages/Login/Login.style.js
  client/src/Components/Pages/Login/index.js
  client/src/Components/Pages/OrgCheck/index.js
  client/src/Components/Pages/Profile/HeaderSection.js
  client/src/Components/Pages/Profile/Profile.style.js
  client/src/Components/Pages/Profile/Reply.js
  client/src/Components/Pages/Profile/ReviewSection.js
  client/src/Components/Pages/Profile/index.js
  client/src/Components/Pages/ReportContent/SelectReason.js
  client/src/Components/Pages/ReportContent/Thanks.js
  client/src/Components/Pages/ResetPassword/Content.js
  client/src/Components/Pages/Review/Question/Options/Rate.js
  client/src/Components/Pages/Review/Review.style.js
  client/src/Components/Pages/Review/index.js
  client/src/Components/Pages/Review/staticQuestions.js
  client/src/Components/Pages/Signup/Signup.style.js
  client/src/Components/Pages/Signup/index.js
  client/src/Components/Pages/Static/PrivacyAndTerms.js
  client/src/Components/Pages/ThankYou/ThankYou.style.js
  client/src/Components/Pages/ThankYou/index.js
  client/src/Components/Pages/UploadImage/UploadImage.style.js
  client/src/Components/Pages/UploadImage/index.js
  client/src/Components/Pages/UserProfile/UserProfile.style.js
  client/src/Components/Pages/UserProfile/index.js
  client/src/Components/Pages/Welcome/Welcome.style.js
  client/src/Components/Pages/Welcome/index.js
  client/src/helpers/index.js
  client/src/theme.js
Labels: awaiting-review

#754 Fix calendar icon on small screens in date picker
  client/src/Components/Common/AntdComponents/AntdComponents.style.js
  client/src/Components/Common/Icon/Calendar.js
Labels: awaiting-review

#748 737 search page
  client/src/Components/Common/GiveReview/index.js
  client/src/Components/Common/Layout/Center.js
  client/src/Components/Common/Layout/Layout.style.js
  client/src/Components/Common/Layout/Side.js
  client/src/Components/Common/Layout/index.js
  client/src/Components/Common/Navbar/Menu.js
  client/src/Components/Common/Navbar/index.js
  client/src/Components/Pages/Admin/SideMenu/index.js
  client/src/Components/Pages/PreReview/PreReview.style.js
  client/src/Components/Pages/PreReview/index.js
  client/src/Components/Pages/Profile/HeaderSection.js
  client/src/Components/Pages/Search/AddProfileReviewStart.js
  client/src/Components/Pages/Search/AddProfileSelection.js
  client/src/Components/Pages/Search/AutoSuggest.js
  client/src/Components/Pages/Search/Header/Header.style.js
  client/src/Components/Pages/Search/Header/Heading.js
  client/src/Components/Pages/Search/Header/Tabs.js
  client/src/Components/Pages/Search/Header/index.js
  client/src/Components/Pages/Search/OrganisationRow.js
  client/src/Components/Pages/Search/OrganisationsList.js
  client/src/Components/Pages/Search/Search.style.js
  client/src/Components/Pages/Search/index.js
  client/src/Components/Pages/Static/TermsOfUse.js
  client/src/Components/Pages/Welcome/Welcome.style.js
  client/src/Components/Pages/Welcome/index.js
  client/src/Components/index.js
  client/src/apiUrls.js
  client/src/constants/naviagationUrls.js
  client/src/helpers/index.js
  server/__test__/api/search.js
  server/__test__/database/queries/search.js
  server/controllers/search.js
  server/database/queries/search.js
Labels: awaiting-review

#750 749 general style
  client/src/Components/Common/Button.js
  client/src/Components/Common/Popover/index.js
  client/src/Components/Pages/Intro/index.js
  client/src/Components/Pages/Login/index.js
  client/src/Components/Pages/Profile/HeaderSection.js
  client/src/Components/Pages/Profile/Profile.style.js
  client/src/Components/Pages/Profile/ProfileAnswers/ProfileAnswers.style.js
  client/src/Components/Pages/Profile/Reply.js
  client/src/Components/Pages/Profile/Reply.style.js
  client/src/Components/Pages/Profile/index.js
  client/src/Components/Pages/Review/index.js
  client/src/Components/Pages/Signup/Signup.style.js
  client/src/Components/Pages/Signup/index.js
  client/src/Components/Pages/Static/CommunityGuidlines.js
  client/src/Components/Pages/Static/CookiesPolicy.js
  client/src/Components/Pages/Static/FAQ.js
  client/src/Components/Pages/Static/HelpfulStuff.js
  client/src/Components/Pages/Static/PrivacyAndTerms.js
  client/src/Components/Pages/Static/PrivacyPolicy.js
  client/src/Components/Pages/Static/ShapeEarwig.js
  client/src/Components/Pages/Static/TermsOfUse.js
  client/src/Components/Pages/ThankYou/index.js
Labels: awaiting-review

#751 734 update review q
  client/package-lock.json
  client/package.json
  client/src/Components/Common/Icon/Warning.js
  client/src/Components/Common/Select.js
  client/src/Components/Pages/EditProfile/EditProfile.style.js
  client/src/Components/Pages/EditProfile/EditProfileSection.js
  client/src/Components/Pages/Profile/OverallReview.js
  client/src/Components/Pages/Profile/ProfileAnswers/BarChartAnswer.js
  client/src/Components/Pages/Profile/ProfileAnswers/CanteenItemAnswer.js
  client/src/Components/Pages/Profile/ProfileAnswers/ListAnswer.js
  client/src/Components/Pages/Profile/ProfileAnswers/PieAnswer.js
  client/src/Components/Pages/Profile/ProfileAnswers/ProfileAnswers.style.js
  client/src/Components/Pages/Profile/ProfileAnswers/SiteItemAnswer.js
  client/src/Components/Pages/Profile/ProfileAnswers/YesNoAnswer.js
  client/src/Components/Pages/Profile/ReviewSection.js
  client/src/Components/Pages/Profile/ReviewSection.style.js
  client/src/Components/Pages/Profile/index.js
  client/src/Components/Pages/Review/Question/Options/DropDown.js
  client/src/Components/Pages/Review/Question/Options/Open.js
  client/src/Components/Pages/Review/Question/Options/OverallReview.js
  client/src/Components/Pages/Review/Question/Options/Rate.js
  client/src/Components/Pages/Review/Question/Options/YesNo.js
  client/src/Components/Pages/Review/Question/Question.style.js
  client/src/Components/Pages/Review/Question/UploadPhoto.js
  client/src/Components/Pages/Review/Question/index.js
  client/src/Components/Pages/Review/staticQuestions.js
  client/src/Components/Pages/Review/validationSchema.js
  client/src/Components/Pages/Search/AutoSuggest.js
  client/src/Components/Pages/Search/Search.style.js
  client/src/Components/Pages/Signup/index.js
  client/src/theme.js
  server/__test__/database/queries/reviews.allQsAndAs.js
  server/__test__/database/queries/reviews.allReviewsIncAs.js
  server/app.js
  server/database/dummyData/answers.js
  server/database/dummyData/comments.js
  server/database/dummyData/index.js
  server/database/dummyData/questions.js
  server/database/queries/reviews/index.js
Labels: awaiting-review, changes-requested

#768 Bug fixes new
  client/src/Components/Pages/Admin/SideMenu/index.js
  client/src/Components/Pages/EditProfile/EditProfileSection.js
  client/src/Components/Pages/Review/index.js
Labels: 1-approval, awaiting-review

#771 refactor sign up page
  client/src/Components/Pages/Signup/Signup.style.js
  client/src/Components/Pages/Signup/index.js
Labels: 1-approval, awaiting-review

#767 Update legal and menu search link
  client/src/Components/Common/Navbar/Menu.js
  client/src/Components/Pages/Static/CookiesPolicy.js
  client/src/Components/Pages/Static/PrivacyPolicy.js
  client/src/Components/Pages/Static/TermsOfUse.js
Labels: 1-approval, awaiting-review

#769 Apply the new layout to the changed pages
  client/src/Components/Common/CancelNavbar.js
  client/src/Components/Common/Layout/Layout.style.js
  client/src/Components/Common/Layout/Side.js
  client/src/Components/Common/Layout/index.js
  client/src/Components/Pages/Profile/HeaderSection.js
  client/src/Components/Pages/Profile/Profile.style.js
  client/src/Components/Pages/Profile/Reply.js
  client/src/Components/Pages/Profile/Reply.style.js
  client/src/Components/Pages/Profile/index.js
  client/src/Components/Pages/ReportContent/index.js
  client/src/Components/Pages/ResetPassword/Content.js
  client/src/Components/Pages/ResetPassword/ResetPassword.style.js
  client/src/Components/Pages/ResetPassword/index.js
  client/src/Components/Pages/Review/Review.style.js
  client/src/Components/Pages/Review/index.js
  client/src/Components/Pages/Static/PrivacyAndTerms.js
Labels: awaiting-review

#773 Improve search performance
  client/src/Components/Pages/Search/Header/Header.style.js
  client/src/Components/Pages/Search/OrganisationsList.js
  client/src/Components/Pages/Search/Search.style.js
  client/src/Components/Pages/Search/index.js
  client/src/helpers/index.js
Labels: awaiting-review

#779 777 non worker header
  client/src/Components/Pages/Profile/HeaderSection.js
  client/src/Components/Pages/Profile/OverallReview.js
  client/src/Components/Pages/Profile/Profile.style.js
  server/database/dummyData/questions.js
Labels: awaiting-review

#778 770 signup bug
  server/__test__/api/user.signup.js
  server/__test__/database/queries/user.addNew.js
  server/controllers/signup.js
  server/database/queries/user/index.js
  server/helpers/3dParty/mailchimp.js
Labels: awaiting-review

#781 Fix categories order
  client/src/helpers/index.js
Labels: awaiting-review

#780 765 design notes (Part 1)
  client/src/Components/Common/AntdComponents/AntdComponents.style.js
  client/src/Components/Common/Navbar/Navbar.style.js
  client/src/Components/Pages/PreReview/PreReview.style.js
  client/src/Components/Pages/Profile/HeaderSection.js
  client/src/Components/Pages/Profile/Profile.style.js
  client/src/Components/Pages/Profile/Reply.js
  client/src/Components/Pages/Profile/ReviewSection.js
  client/src/Components/Pages/Review/Question/Options/Number.js
  client/src/Components/Pages/Review/Question/Options/Rate.js
  client/src/Components/Pages/Review/Question/Options/YesNo.js
  client/src/Components/Pages/Review/Question/Question.style.js
  client/src/Components/Pages/Review/Question/index.js
  client/src/Components/Pages/Review/Review.style.js
  client/src/Components/Pages/Review/index.js
  client/src/Components/Pages/Review/staticQuestions.js
  client/src/Components/Pages/Search/Header/Header.style.js
  client/src/Components/Pages/Search/Header/index.js
  client/src/Components/Pages/Search/Search.style.js
  client/src/Components/Pages/UserProfile/UserReviews.js
  client/src/Components/Pages/Welcome/Welcome.style.js
  client/src/Components/Pages/Welcome/index.js
  client/src/Components/index.js
Labels: awaiting-review

#776 Profile tooltip bugs
  client/src/Components/Common/AntdComponents/AntdComponents.style.js
  client/src/Components/Common/AntdComponents/DatePicker.js
  client/src/Components/Common/GiveReview/index.js
  client/src/Components/Pages/Profile/HeaderSection.js
  client/src/Components/Pages/Profile/ProfileAnswers/ListAnswer.js
  client/src/Components/Pages/Profile/ProfileAnswers/YesNoAnswer.js
  client/src/Components/Pages/Profile/ReviewSection.js
  client/src/Components/Pages/Review/Question/Options/Number.js
  client/src/Components/Pages/Review/Question/Question.style.js
  client/src/Components/Pages/Review/Question/index.js
  client/src/Components/Pages/Review/Review.style.js
  client/src/Components/Pages/Review/index.js
  client/src/Components/Pages/Review/staticQuestions.js
  server/database/dummyData/questions.js
Labels: awaiting-review

#782 Render car price > #775
  client/src/Components/Pages/Profile/ProfileAnswers/SiteItemAnswer.js
  client/src/Components/Pages/Profile/index.js
  server/database/dummyData/questions.js
Labels: awaiting-review

#785 784 samsung
  client/public/index.html
  client/src/Components/Pages/Review/Review.style.js
Labels: awaiting-review

#786 783 copy updates
  client/src/Components/Common/Button.js
  client/src/Components/Pages/DeleteProfile/index.js
  client/src/Components/Pages/EditProfile/EditProfileSection.js
  client/src/Components/Pages/EditProfile/index.js
  client/src/Components/Pages/Signup/Signup.style.js
  client/src/Components/Pages/Signup/index.js
  client/src/Components/Pages/UploadImage/UploadImage.style.js
  client/src/Components/Pages/UploadImage/index.js
  client/src/Components/Pages/UserProfile/UserProfile.style.js
  client/src/Components/Pages/UserProfile/index.js
Labels: awaiting-review

#799 Delete old irrelevant old answers based on the questions flow.
  client/package-lock.json
  client/src/Components/Pages/Review/Question/Options/YesNo.js
  client/src/Components/Pages/Review/index.js
  package-lock.json
Labels: awaiting-review

#797 790 level 1 limitation
  client/src/Components/Pages/Profile/Profile.style.js
  client/src/Components/Pages/Review/Review.style.js
  server/database/queries/reviews/index.js
Labels: awaiting-review

#809 Updates to reviewing pages
  client/src/Components/Pages/Profile/index.js
  client/src/Components/Pages/Review/Question/Options/Rate.js
  client/src/Components/Pages/Review/index.js
  client/src/Components/Pages/Review/staticQuestions.js
  server/constants.js
  server/database/dummyData/answers.js
  server/database/dummyData/questions.js
Labels: awaiting-review

#810 Remove question-specific commenting altogether
  client/src/Components/Pages/Profile/ProfileAnswers/ListAnswer.js
  client/src/Components/Pages/Profile/ProfileAnswers/PieAnswer.js
  client/src/Components/Pages/Profile/ProfileAnswers/SiteItemAnswer.js
  client/src/Components/Pages/Profile/ProfileAnswers/YesNoAnswer.js
  client/src/Components/Pages/Review/Question/Options/YesNo.js
  client/src/Components/Pages/Review/Question/index.js
  server/controllers/admin/getAllReviewsCSV.js
Labels: awaiting-review

#812 806 update profile page
  client/src/Components/Common/Button.js
  client/src/Components/Common/Icon/Detailed.js
  client/src/Components/Common/Icon/Icon.js
  client/src/Components/Common/Icon/Overview.js
  client/src/Components/Common/Layout/Layout.style.js
  client/src/Components/Common/Navbar/Navbar.style.js
  client/src/Components/Pages/Profile/DetailedSection/DetailedAnswers.js
  client/src/Components/Pages/Profile/DetailedSection/ReviewSection.js
  client/src/Components/Pages/Profile/DetailedSection/ReviewSection.style.js
  client/src/Components/Pages/Profile/DetailedSection/index.js
  client/src/Components/Pages/Profile/HeaderSection.js
  client/src/Components/Pages/Profile/OverviewSection/ContractorsList.js
  client/src/Components/Pages/Profile/OverviewSection/Level0Promo.js
  client/src/Components/Pages/Profile/OverviewSection/OrganisationDetails.js
  client/src/Components/Pages/Profile/OverviewSection/OverallReview.js
  client/src/Components/Pages/Profile/OverviewSection/index.js
  client/src/Components/Pages/Profile/Profile.style.js
  client/src/Components/Pages/Profile/ProfileAnswers/CommentsBox.js
  client/src/Components/Pages/Profile/ProfileAnswers/SiteItemAnswer.js
  client/src/Components/Pages/Profile/SignUpSection.js
  client/src/Components/Pages/Profile/index.js
  client/src/Components/Pages/Profile/utils.js
Labels: awaiting-review

#815 Fix the tooltip icon size
  client/src/Components/Common/ToolTip.js
  client/src/Components/Pages/Review/Question/index.js
  client/src/Components/Pages/Review/staticQuestions.js
Labels: awaiting-review

#816 Update the sorting order for the orgs list to account for special charachters
  client/src/helpers/index.js
  server/controllers/search.js
Labels: awaiting-review

#820 801 design update welcome search pages
  client/src/Components/Common/Layout/Center.js
  client/src/Components/Common/Layout/Layout.style.js
  client/src/Components/Common/Navbar/index.js
  client/src/Components/Pages/PreReview/index.js
  client/src/Components/Pages/Search/Header/Header.style.js
  client/src/Components/Pages/Search/Header/index.js
  client/src/Components/Pages/Search/Search.style.js
  client/src/Components/Pages/Welcome/Welcome.style.js
  client/src/Components/Pages/Welcome/index.js
  client/src/assets/downward-arrow.svg
  client/src/assets/earwig-logo-white.png
  client/src/assets/welcome_page_image_desktop.jpg
  client/src/assets/welcome_page_image_mobile.jpg
Labels: awaiting-review

#821 fix navbar bug
  client/src/Components/Pages/Profile/HeaderSection.js
Labels: awaiting-review

#817 805 update review style
  client/src/Components/Common/Icon/VoiceRecord.js
  client/src/Components/Pages/Landing/index.js
  client/src/Components/Pages/Profile/DetailedSection/DetailedAnswers.js
  client/src/Components/Pages/Profile/DetailedSection/ReviewSection.js
  client/src/Components/Pages/Profile/DetailedSection/ReviewSection.style.js
  client/src/Components/Pages/Profile/OverviewSection/OverallReview.js
  client/src/Components/Pages/Profile/Profile.style.js
  client/src/Components/Pages/Profile/ProfileAnswers/ProfileAnswers.style.js
  client/src/Components/Pages/Profile/ProfileAnswers/SiteItemAnswer.js
  client/src/Components/Pages/Profile/ProfileAnswers/YesNoAnswer.js
  client/src/Components/Pages/Profile/utils.js
Labels: awaiting-review

#824 Fix worksite render and give profile crashing
  client/src/Components/Pages/Profile/DetailedSection/DetailedAnswers.js
  client/src/Components/Pages/Profile/HeaderSection.js
  client/src/Components/Pages/Profile/index.js
  client/src/Components/Pages/Profile/utils.js
  server/constants.js
  server/database/dummyData/questions.js
Labels: awaiting-review

#830 829 stars width
  client/src/Components/Pages/Profile/OverviewSection/OverallReview.js
  client/src/Components/Pages/Profile/Profile.style.js
  client/src/Components/Pages/Search/Search.style.js
Labels: awaiting-review

#838 make cancel review link redirect to profile page
  client/src/Components/Pages/Review/index.js
Labels: awaiting-review

#839 add search icon to the navbar
  client/src/Components/Common/Navbar/index.js
Labels: awaiting-review

#840 shrink input height by default
  client/src/Components/Pages/Search/Header/index.js
Labels: awaiting-review

#842 841 select components spaces
  client/src/Components/Common/CancelNavbar.js
  client/src/Components/Common/Select.js
  client/src/Components/Pages/EditProfile/EditProfileSection.js
  client/src/Components/Pages/ReportContent/SelectReason.js
  client/src/Components/Pages/Review/Question/Options/DropDown.js
  client/src/Components/Pages/Review/index.js
  client/src/Components/Pages/Signup/index.js
  client/src/Components/Pages/UploadImage/index.js
Labels: awaiting-review

#843 fix menu icon width
  client/src/Components/Common/Navbar/Menu.style.js
  client/src/Components/Common/Navbar/Navbar.style.js
  client/src/Components/Common/Navbar/index.js
Labels: awaiting-review

#844 832 questions order
  client/src/Components/Pages/InviteWorkers/index.js
  client/src/Components/Pages/InviteWorkers/inviteWorkers.style.js
  client/src/assets/email-logo.svg
  client/src/assets/messenger-logo.svg
  client/src/assets/whatsapp-logo.svg
  package.json
  server/database/dbConnection.js
  server/database/dummyData/index.js
  server/database/dummyData/questions.js
  server/database/dummyData/resetDB.js
Labels: awaiting-review

#818 802 update other pages
  client/src/Components/Common/Layout/CentredBluePurpleLayout.js
  client/src/Components/Common/Link.js
  client/src/Components/Pages/EditProfile/EditProfileSection.js
  client/src/Components/Pages/InviteWorkers/index.js
  client/src/Components/Pages/InviteWorkers/inviteWorkers.style.js
  client/src/Components/Pages/Profile/ProfileAnswers/ScatterAnswer.js
  client/src/Components/Pages/Profile/index.js
  client/src/Components/Pages/Static/FAQ.js
  client/src/Components/Pages/Static/HelpfulStuff.js
  client/src/Components/Pages/Static/PrivacyAndTerms.js
  client/src/Components/Pages/Static/ShapeEarwig.js
  client/src/Components/Pages/UserProfile/UserProfile.style.js
  client/src/Components/Pages/UserProfile/UserReviews.js
  client/src/Components/index.js
  server/controllers/userReviews.js
  server/database/queries/reviews/getUserReviews.js
Labels: awaiting-review
