Repository yalla-coop/earwig, pull requests merged in 2019-04, with the labels that each got.

#15 Codebase
  .eslintrc.json
  client/.eslintrc.json
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/Components/index.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/serviceWorker.js
  client/src/setupProxy.js
  codecov.yml
  package-lock.json
  package.json
  server/__test__/initial_test.js
  server/app.js
  server/bin/www.js
  server/router/controllers/hello.js
  server/router/controllers/index.js
  server/router/index.js
Labels: awaiting-review

#41 Add travis config file
  .travis.yml
Labels: awaiting-review

#42 refactor: changes to filesturcture
  client/package-lock.json
  client/src/index.js
  client/src/logo.svg
  client/src/serviceWorker.js
  package-lock.json
  package.json
  server/app.js
  server/controllers/auth.js
  server/controllers/hello.js
  server/database/dbConnection.js
  server/middlewares/validation.js
  server/router/controllers/index.js
  server/router/index.js
Labels: awaiting-review

#45 Css variables
  client/public/index.html
  client/src/App.js
  client/src/Components/theme.js
  client/src/index.css
Labels: awaiting-review

#43 Db schema
  package-lock.json
  package.json
  server/__test__/database/schema/job.js
  server/__test__/database/schema/organization.js
  server/__test__/database/schema/questions.js
  server/__test__/database/schema/review.js
  server/__test__/database/schema/trade.js
  server/__test__/database/schema/user.js
  server/constants.js
  server/database/dbConnection.js
  server/database/dummyData/answers.js
  server/database/dummyData/comments.js
  server/database/dummyData/index.js
  server/database/dummyData/jobs.js
  server/database/dummyData/organizations.js
  server/database/dummyData/questions.js
  server/database/dummyData/resetDB.js
  server/database/dummyData/reviews.js
  server/database/dummyData/trades.js
  server/database/dummyData/users.js
  server/database/models/Answer.js
  server/database/models/Comment.js
  server/database/models/Job.js
  server/database/models/Organization.js
  server/database/models/Question.js
  server/database/models/Review.js
  server/database/models/Trade.js
  server/database/models/User.js
Labels: in-progress

#80 [chore] Add the rest of the dummy data
  server/__test__/database/schema/answers.js
  server/__test__/database/schema/questions.js
  server/database/dummyData/answers.js
  server/database/dummyData/questions.js
Labels: awaiting-review

#82 Fix rem value
  client/src/App.js
  client/src/index.css
Labels: awaiting-review

#84 Thank you page
  client/public/index.html
  client/src/Components/Pages/ThankYou/ThankYou.style.js
  client/src/Components/Pages/ThankYou/index.js
  client/src/Components/index.js
  client/src/Components/theme.js
  client/src/assets/thank-you-agency.svg
  client/src/assets/thank-you-company.svg
  client/src/assets/thank-you-payroll.svg
  client/src/assets/thank-you-worksite.svg
Labels: awaiting-review

#79 Login
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Components/Common/Formik/Formik.style.js
  client/src/Components/Pages/Login/Login.style.js
  client/src/Components/Pages/Login/index.js
  client/src/Components/index.js
  client/src/Components/theme.js
  client/src/assets/logo.svg
  package-lock.json
  package.json
  server/__test__/api/user.login.js
  server/__test__/database/queries/user.findByEmail.js
  server/app.js
  server/bin/www.js
  server/controllers/login.js
  server/database/queries/index.js
  server/database/queries/user/index.js
  server/middlewares/validation.js
  server/router/index.js
Labels: awaiting-review, justen-review

#86 Upload verification photo
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Components/Common/Select.js
  client/src/Components/Pages/UploadImage/UploadImage.style.js
  client/src/Components/Pages/UploadImage/index.js
  client/src/Components/index.js
  client/src/assets/card.svg
  client/src/assets/example.png
  package-lock.json
  package.json
  server/__test__/api/addTrade.js
  server/__test__/api/getTrades.js
  server/__test__/database/queries/trade.getTrades.js
  server/__test__/database/queries/user.findByIdAndUpdate.js
  server/app.js
  server/bin/www.js
  server/config.js
  server/controllers/addTrade.js
  server/controllers/getTrades.js
  server/controllers/uploadVerificationImage.js
  server/database/queries/index.js
  server/database/queries/user/index.js
  server/middlewares/deleteFileFromServer.js
  server/middlewares/uploadFileToServer.js
  server/middlewares/uploadToGoogle.js
  server/middlewares/validation.js
  server/router/index.js
  uploads/.gitkeep
Labels: awaiting-review

#85 Rebased navbar
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/public/icons/contact-icon.svg
  client/public/icons/faq-icon.svg
  client/public/icons/jobs-icon.svg
  client/public/icons/links-icon.svg
  client/public/icons/log-out-icon.svg
  client/public/icons/mobile-search-icon.svg
  client/public/icons/profile-icon.svg
  client/public/icons/tcs-icon.svg
  client/public/icons/win-icon.svg
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/Components/Common/Formik/Formik.style.js
  client/src/Components/Common/Navbar/Menu.js
  client/src/Components/Common/Navbar/Menu.style.js
  client/src/Components/Common/Navbar/Navbar.style.js
  client/src/Components/Common/Navbar/index.js
  client/src/Components/Pages/Login/Login.style.js
  client/src/Components/Pages/Signup/Signup.style.js
  client/src/Components/Pages/ThankYou/ThankYou.style.js
  client/src/Components/Pages/UploadImage/UploadImage.style.js
  client/src/Components/index.js
  client/src/assets/close-icon.svg
  client/src/assets/hamburger-icon.svg
  client/src/assets/logo.svg
  client/src/assets/search-icon.svg
  client/src/constants/naviagationUrls.js
  client/src/constants/screenWidths.js
  client/src/helpers.js
  client/src/index.css
  client/src/theme.js
  package-lock.json
  server/__test__/database/queries/user.findByEmail.js
  server/bin/www.js
  server/controllers/login.js
  server/middlewares/validation.js
Labels: awaiting-review

#90 Authentication and Authorization
  client/src/Components/Pages/ThankYou/index.js
  server/app.js
  server/database/queries/user/index.js
  server/middlewares/authentication.js
  server/middlewares/authorization.js
Labels: awaiting-review

#98 Static pages
  client/src/Components/Common/Navbar/Menu.js
  client/src/Components/Common/Navbar/index.js
  client/src/Components/Pages/Static/FAQ.js
  client/src/Components/Pages/Static/HelpfulStuff.js
  client/src/Components/Pages/Static/PrivacyAndTerms.js
  client/src/Components/Pages/Static/ShapeEarwig.js
  client/src/Components/Pages/Static/Static.style.js
  client/src/Components/Pages/Static/index.js
  client/src/Components/index.js
  client/src/assets/lamp-icon.svg
  client/src/assets/link-icon.svg
  client/src/assets/paper-icon.svg
  client/src/assets/question-mark.svg
  client/src/constants/naviagationUrls.js
  client/src/theme.js
Labels: awaiting-review

#92 Organization review
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/Components/Common/Rater.js
  client/src/Components/Pages/Review/Question/Question.style.js
  client/src/Components/Pages/Review/Question/UploadPhoto.js
  client/src/Components/Pages/Review/Question/UploadPhoto.style.js
  client/src/Components/Pages/Review/Question/index.js
  client/src/Components/Pages/Review/Review.style.js
  client/src/Components/Pages/Review/index.js
  client/src/Components/Pages/Review/initialQuestionsValues.js
  client/src/Components/Pages/Review/validationSchema.js
  client/src/Components/index.js
  client/src/apiUrls.js
  client/src/assets/agency-icon.svg
  client/src/assets/clock-long-icon.svg
  client/src/assets/clock-short-icon.svg
  client/src/assets/comment-icon.svg
  client/src/assets/upload-worksite-icon.svg
  package-lock.json
  server/__test__/database/schema/questions.js
  server/app.js
  server/controllers/review.js
  server/controllers/uploadWorksiteImage.js
  server/database/dummyData/questions.js
  server/database/models/Question.js
  server/database/models/Review.js
  server/database/queries/review.js
  server/middlewares/validation.js
  server/router/index.js
Labels: awaiting-review, justen-review

#95 Edit profile
  client/src/Components/Common/Formik/Formik.style.js
  client/src/Components/Pages/EditProfile/EditProfile.style.js
  client/src/Components/Pages/EditProfile/index.js
  client/src/Components/Pages/UploadImage/index.js
  client/src/Components/index.js
  client/src/assets/card-hand.svg
  client/src/constants/naviagationUrls.js
  client/src/theme.js
  server/__test__/api/addTrade.js
  server/__test__/api/getTrades.js
  server/__test__/api/updateUserProfile.js
  server/controllers/editProfile.js
  server/controllers/login.js
  server/database/queries/user/index.js
  server/middlewares/authentication.js
  server/middlewares/deleteFileFromServer.js
  server/middlewares/uploadToGoogle.js
  server/middlewares/validation.js
  server/router/index.js
Labels: awaiting-review

#88 Search functionality rendering
  client/package-lock.json
  client/package.json
  client/public/icons/add-item-icon.svg
  client/public/icons/agency-arrow.svg
  client/public/icons/agency-icon.svg
  client/public/icons/arrow-back-icon.svg
  client/public/icons/company-arrow.svg
  client/public/icons/company-icon.svg
  client/public/icons/mobile-search-icon.svg
  client/public/icons/payroll-arrow.svg
  client/public/icons/payroll-icon.svg
  client/public/icons/worksite-arrow.svg
  client/public/icons/worksite-icon.svg
  client/src/Components/Pages/Search/Search.style.js
  client/src/Components/Pages/Search/Search.test.js
  client/src/Components/Pages/Search/index.js
  client/src/Components/Pages/Search/resultArray.js
  client/src/Components/index.js
  client/src/__mocks__/axios.js
  client/src/apiUrls.js
  client/src/helpers.js
  client/src/theme.js
  server/__test__/api/search.js
  server/__test__/database/queries/search.js
  server/controllers/search.js
  server/database/dummyData/answers.js
  server/database/dummyData/organizations.js
  server/database/models/Organization.js
  server/database/queries/search.js
  server/router/index.js
Labels: awaiting-review, justen-review

#104 Profiles
  client/package-lock.json
  client/package.json
  client/public/icons/agency-icon-desktop.svg
  client/public/icons/arrow-icon.svg
  client/public/icons/clock-2min.svg
  client/public/icons/clock-30s.svg
  client/public/icons/company-icon-desktop.svg
  client/public/icons/not-tick-icon.svg
  client/public/icons/or-horizontal.svg
  client/public/icons/or-vertical.svg
  client/public/icons/payroll-icon-desktop.svg
  client/public/icons/speech-icon.svg
  client/public/icons/tick-icon.svg
  client/public/icons/worksite-icon-desktop.svg
  client/src/App.js
  client/src/Components/Common/GiveReview/GiveReview.style.js
  client/src/Components/Common/GiveReview/index.js
  client/src/Components/Common/Navbar/Navbar.style.js
  client/src/Components/Pages/Profile/HeaderSection.js
  client/src/Components/Pages/Profile/Profile.style.js
  client/src/Components/Pages/Profile/ProfileAnswers/BarAnswer.js
  client/src/Components/Pages/Profile/ProfileAnswers/CanteenItemAnswer.js
  client/src/Components/Pages/Profile/ProfileAnswers/CommentsBox.js
  client/src/Components/Pages/Profile/ProfileAnswers/ListAnswer.js
  client/src/Components/Pages/Profile/ProfileAnswers/PieAnswer.js
  client/src/Components/Pages/Profile/ProfileAnswers/ProfileAnswers.style.js
  client/src/Components/Pages/Profile/ProfileAnswers/ScatterAnswer.js
  client/src/Components/Pages/Profile/ProfileAnswers/SiteItemAnswer.js
  client/src/Components/Pages/Profile/ProfileAnswers/YesNoAnswer.js
  client/src/Components/Pages/Profile/ReviewSection.js
  client/src/Components/Pages/Profile/ReviewSection.style.js
  client/src/Components/Pages/Profile/index.js
  client/src/Components/index.js
  client/src/constants/promoItems.js
  client/src/constants/screenWidths.js
  client/src/helpers.js
  client/src/theme.js
  package-lock.json
  server/__test__/api/reviews.comments.js
  server/__test__/api/reviews.profile.js
  server/__test__/database/queries/reviews.allAnswers.js
  server/__test__/database/queries/reviews.allComments.js
  server/__test__/database/queries/reviews.basicReview.js
  server/__test__/database/queries/reviews.checkOrgExists.js
  server/__test__/database/queries/reviews.overallReview.js
  server/__test__/database/schema/questions.js
  server/__test__/database/schema/review.js
  server/constants.js
  server/controllers/basicprofile.js
  server/controllers/comments.js
  server/controllers/profile.js
  server/database/dummyData/answers.js
  server/database/dummyData/comments.js
  server/database/dummyData/questions.js
  server/database/models/Answer.js
  server/database/models/Question.js
  server/database/queries/reviews/index.js
  server/middlewares/softAuthCheck.js
  server/router/index.js
Labels: awaiting-review

#103 Admin all users
  client/src/Components/Pages/Admin/Users/AllUsers.js
  client/src/Components/Pages/Admin/Users/Users.style.js
  client/src/Components/Pages/Admin/Users/UsersColumns.js
  client/src/Components/Pages/Admin/Users/VerifyUser.js
  client/src/Components/Pages/Admin/Users/index.js
  client/src/constants/adminRoutes.js
  server/__test__/api/admin/deleteUser.js
  server/__test__/api/admin/getAllUsers.js
  server/__test__/api/admin/rejectUser.js
  server/__test__/api/admin/verifyUser.js
  server/config.js
  server/controllers/admin/allUsers.js
  server/controllers/admin/deleteUser.js
  server/controllers/admin/rejectUser.js
  server/controllers/admin/userInfo.js
  server/controllers/admin/verifyUser.js
  server/database/queries/user/allUsers.js
  server/database/queries/user/index.js
  server/helpers/deleteFile.js
  server/helpers/getFileLink.js
  server/middlewares/uploadToGoogle.js
  server/router/admin.js
  server/router/index.js
Labels: awaiting-review

#106 Add item
  client/public/icons/agency-category.svg
  client/public/icons/company-category.svg
  client/public/icons/payroll-category.svg
  client/public/icons/worksite-category.svg
  client/src/Components/Common/GiveReview/index.js
  client/src/Components/Common/Navbar/Navbar.style.js
  client/src/Components/Common/Navbar/index.js
  client/src/Components/Pages/Profile/HeaderSection.js
  client/src/Components/Pages/Review/index.js
  client/src/Components/Pages/Search/AddProfileReviewStart.js
  client/src/Components/Pages/Search/AddProfileSelection.js
  client/src/Components/Pages/Search/AutoSuggest.js
  client/src/Components/Pages/Search/Search.style.js
  client/src/Components/Pages/Search/Search.test.js
  client/src/Components/Pages/Search/index.js
  client/src/Components/index.js
  client/src/assets/placeholder-arrow.svg
  client/src/constants/naviagationUrls.js
  client/src/helpers.js
Labels: awaiting-review

#109 Mail list
  client/package-lock.json
  client/src/Components/Pages/JoinMailList/JoinMailList.style.js
  client/src/Components/Pages/JoinMailList/index.js
  client/src/Components/index.js
  package-lock.json
  package.json
  server/assets/logo.png
  server/controllers/confirmJoiningEmailList.js
  server/controllers/signup.js
  server/database/dummyData/index.js
  server/database/dummyData/mailList.js
  server/database/dummyData/resetDB.js
  server/database/models/MailList.js
  server/database/queries/mailList/index.js
  server/helpers/confirmJoiningMailList.js
  server/helpers/mailer.js
  server/middlewares/validation.js
  server/router/index.js
Labels: awaiting-review

#111 View all trades + delete trade (Admin panel)
  client/src/Components/Pages/Admin/Trades/index.js
  client/src/Components/Pages/Admin/index.js
  server/controllers/admin/trades.js
  server/database/queries/index.js
  server/router/admin.js
Labels: awaiting-review

#110 Admin orgs
  client/src/App.css
  client/src/Components/Pages/Admin/Organizations/AllOrganizations.js
  client/src/Components/Pages/Admin/Organizations/OrganizationsColumns.js
  client/src/Components/Pages/Admin/Organizations/index.js
  client/src/Components/Pages/Admin/Users/AllUsers.js
  client/src/Components/Pages/Admin/Users/VerifyUser.js
  server/__test__/api/admin/activateOrganization.js
  server/__test__/api/admin/getOrganizations.js
  server/controllers/admin/activateOrganization.js
  server/controllers/admin/getOrganizations.js
  server/controllers/comments.js
  server/controllers/profile.js
  server/database/models/Organization.js
  server/database/queries/organizations/getOrgsByCategory.js
  server/database/queries/organizations/index.js
  server/middlewares/validation.js
  server/router/admin.js
  server/router/index.js
Labels: awaiting-review

#114 Admin review
  client/src/Components/Pages/Admin/Reviews/AllReviews.js
  client/src/Components/Pages/Admin/Reviews/ReviewsColumns.js
  client/src/Components/Pages/Admin/Reviews/index.js
  server/__test__/api/admin/deleteReview.js
  server/__test__/api/admin/getAllReviews.js
  server/controllers/admin/deleteReview.js
  server/controllers/admin/getReviews.js
  server/database/queries/reviews/allReviews.js
  server/database/queries/reviews/index.js
  server/middlewares/validation.js
  server/router/admin.js
Labels: awaiting-review

#117 Fix trade authorization and fix image uploading
  server/controllers/uploadVerificationImage.js
  server/router/index.js
Labels: awaiting-review, bug

#115 Logout
  client/package-lock.json
  client/src/Components/Common/Icon/Icon.js
  client/src/Components/Common/Icon/LogoutLogin.js
  client/src/Components/Common/Icon/log-out-icon.svg
  client/src/Components/Common/Navbar/Menu.js
  client/src/Components/Common/Navbar/Menu.style.js
  client/src/apiUrls.js
  client/src/helpers.js
  server/controllers/logout.js
  server/router/index.js
Labels: awaiting-review

#144 Review style refactor + add rangeDatePicker
  client/package-lock.json
  client/src/Components/Common/AntdComponents/DatePicker.js
  client/src/Components/Common/Rater.js
  client/src/Components/Pages/QuickReview/index.js
  client/src/Components/Pages/Review/Question/Question.style.js
  client/src/Components/Pages/Review/Question/UploadPhoto.js
  client/src/Components/Pages/Review/Question/index.js
  client/src/Components/Pages/Review/Review.style.js
  client/src/Components/Pages/Review/index.js
  client/src/Components/Pages/Review/initialQuestionsValues.js
  client/src/Components/Pages/Review/staticQuestions.js
  client/src/Components/Pages/Review/validationSchema.js
  client/src/helpers.js
  client/src/theme.js
  package-lock.json
  server/controllers/review.js
  server/database/dummyData/questions.js
Labels: awaiting-review

#146 Report content
  client/src/Components/Common/Select.js
  client/src/Components/Common/StaticPages.style.js
  client/src/Components/Pages/Profile/Profile.style.js
  client/src/Components/Pages/Profile/ProfileAnswers/CommentsBox.js
  client/src/Components/Pages/Profile/ProfileAnswers/ProfileAnswers.style.js
  client/src/Components/Pages/Profile/index.js
  client/src/Components/Pages/ReportContent/GiveInformation.js
  client/src/Components/Pages/ReportContent/SelectReason.js
  client/src/Components/Pages/ReportContent/Thanks.js
  client/src/Components/Pages/ReportContent/index.js
  client/src/Components/Pages/Static/FAQ.js
  client/src/Components/Pages/Static/HelpfulStuff.js
  client/src/Components/Pages/Static/PrivacyAndTerms.js
  client/src/Components/Pages/Static/ShapeEarwig.js
  client/src/Components/index.js
  client/src/apiUrls.js
  client/src/assets/check-icon.svg
  client/src/assets/flag.svg
  client/src/constants/naviagationUrls.js
  server/__test__/api/reportContent.js
  server/controllers/reportContent.js
  server/helpers/reportMailing.js
  server/middlewares/validation.js
  server/router/index.js
Labels: awaiting-review

#147 User location
  client/src/Components/Pages/Admin/Users/UsersColumns.js
  client/src/Components/Pages/UploadImage/UploadImage.style.js
  client/src/Components/Pages/UploadImage/index.js
  client/src/apiUrls.js
  server/controllers/uploadVerificationImage.js
  server/database/models/User.js
  server/database/queries/user/allUsers.js
  server/middlewares/validation.js
Labels: awaiting-review

#137 Single review admin
  client/public/icons/delete-icon.svg
  client/src/Components/Pages/Admin/Reviews/ReviewsColumns.js
  client/src/Components/Pages/Admin/Reviews/SingleReview.js
  client/src/Components/Pages/Admin/Reviews/index.js
  client/src/Components/Pages/Review/Question/Question.style.js
  client/src/Components/Pages/Review/Question/index.js
  client/src/Components/Pages/Review/Review.style.js
  client/src/Components/Pages/Review/index.js
  client/src/constants/adminRoutes.js
  client/src/helpers.js
  server/__test__/api/admin/deleteReviewAnswer.js
  server/__test__/api/admin/getSingleReview.js
  server/__test__/api/admin/updateSingleReview.js
  server/__test__/database/queries/reviews.getDetails.js
  server/controllers/admin/deleteReviewAnswer.js
  server/controllers/admin/getReviews.js
  server/controllers/admin/getSingleReview.js
  server/controllers/admin/handleSingleReviewStatus.js
  server/database/queries/reviews/allReviews.js
  server/database/queries/reviews/getReviewDetails.js
  server/database/queries/reviews/index.js
  server/router/admin.js
  server/router/index.js
Labels: awaiting-review

#152 Add Landing page
  client/src/Components/Common/Formik/Formik.style.js
  client/src/Components/Common/Icon/Icon.js
  client/src/Components/Common/Icon/MedalIcon1.js
  client/src/Components/Common/Icon/MedalIcon2.js
  client/src/Components/Common/Icon/Or-White.svg
  client/src/Components/Common/Icon/OrWhite.js
  client/src/Components/Common/Icon/TrophyIcon1.js
  client/src/Components/Common/Icon/TrophyIcon2.js
  client/src/Components/Common/Icon/medal-icon-2.svg
  client/src/Components/Common/Icon/medal-icon.svg
  client/src/Components/Common/Icon/trophy-icon-2.svg
  client/src/Components/Common/Icon/trophy-icon.svg
  client/src/Components/Pages/Landing/Landing.style.js
  client/src/Components/Pages/Landing/index.js
  client/src/Components/index.js
  client/src/assets/logo-white.png
  client/src/theme.js
Labels: awaiting-review

#153 Add payroll answer
  client/src/Components/Pages/Profile/ProfileAnswers/ListAnswer.js
  client/src/Components/Pages/Profile/ProfileAnswers/PieAnswer.js
  client/src/Components/Pages/Profile/ProfileAnswers/ProfileAnswers.style.js
  client/src/Components/Pages/Profile/ProfileAnswers/ScatterAnswer.js
Labels: awaiting-review

#155 fix: worksite review submit bug
  client/src/Components/Pages/Landing/index.js
  client/src/Components/Pages/QuickReview/index.js
  client/src/Components/Pages/Review/index.js
  client/src/Components/Pages/Review/initialQuestionsValues.js
Labels: awaiting-review

#159 Profile Fixes & Send Feedback
  client/public/icons/agency-arrow.svg
  client/public/icons/company-arrow.svg
  client/public/icons/or-horizontal.svg
  client/public/icons/or-vertical.svg
  client/public/icons/payroll-arrow.svg
  client/public/icons/worksite-arrow.svg
  client/src/Components/Common/CommentSection/CommentBox.style.js
  client/src/Components/Common/CommentSection/index.js
  client/src/Components/Common/Icon/Bus.js
  client/src/Components/Common/Icon/Canteen.js
  client/src/Components/Common/Icon/CheapFood.js
  client/src/Components/Common/Icon/Fingerprint.js
  client/src/Components/Common/Icon/HotFood.js
  client/src/Components/Common/Icon/Icon.js
  client/src/Components/Common/Icon/Lockers.js
  client/src/Components/Common/Icon/Or-White.svg
  client/src/Components/Common/Icon/OrHorizontal.js
  client/src/Components/Common/Icon/OrWhite.js
  client/src/Components/Common/Icon/OrganisationalRatings.js
  client/src/Components/Common/Icon/ParkingSign.js
  client/src/Components/Common/Icon/PayrollCharges.js
  client/src/Components/Common/Icon/PrayerRoom.js
  client/src/Components/Common/Icon/Support.js
  client/src/Components/Common/Icon/Water.js
  client/src/Components/Common/Icon/WelfareSafety.js
  client/src/Components/Common/Icon/medal-icon-2.svg
  client/src/Components/Common/Icon/medal-icon.svg
  client/src/Components/Common/Icon/new-agency.svg
  client/src/Components/Common/Icon/trophy-icon-2.svg
  client/src/Components/Common/Icon/trophy-icon.svg
  client/src/Components/Common/Navbar/Menu.js
  client/src/Components/Common/StaticPages.style.js
  client/src/Components/Pages/DeleteProfile/index.js
  client/src/Components/Pages/Landing/Landing.style.js
  client/src/Components/Pages/Landing/index.js
  client/src/Components/Pages/Profile/Profile.style.js
  client/src/Components/Pages/Profile/ProfileAnswers/CanteenItemAnswer.js
  client/src/Components/Pages/Profile/ProfileAnswers/ProfileAnswers.style.js
  client/src/Components/Pages/Profile/ProfileAnswers/SiteItemAnswer.js
  client/src/Components/Pages/Profile/index.js
  client/src/Components/Pages/Static/FAQ.js
  client/src/Components/Pages/Static/HelpfulStuff.js
  client/src/Components/Pages/Static/ShapeEarwig.js
  client/src/Components/index.js
  client/src/constants/promoItems.js
  server/__test__/api/feedback.js
  server/controllers/feedback.js
  server/controllers/profile.js
  server/database/dummyData/answers.js
  server/database/dummyData/questions.js
  server/database/models/Question.js
  server/router/index.js
Labels: awaiting-review

#160 Slider
  client/src/Components/Common/Icon/Icon.js
  client/src/Components/Common/Icon/LeftArrow.js
  client/src/Components/Common/Icon/RightArrow.js
  client/src/Components/Pages/Profile/ProfileAnswers/ImageSlider.js
  client/src/Components/Pages/Profile/ProfileAnswers/ProfileAnswers.style.js
  client/src/Components/Pages/Profile/ProfileAnswers/Slider.css
  client/src/Components/Pages/Profile/ReviewSection.js
  client/src/Components/Pages/Review/index.js
  client/src/Components/index.js
  client/src/assets/clock-long-icon.png
  client/src/assets/clock-short-icon.png
  client/src/assets/leftarrowicon.svg
  client/src/assets/right-arrow.icon.svg
  server/controllers/getWorksiteImgs.js
  server/controllers/review.js
  server/database/dummyData/answers.js
  server/database/dummyData/questions.js
  server/helpers/getFileLink.js
  server/router/index.js
Labels: awaiting-review
