Repository yalla-coop/earwig, pull requests merged in 2019-12, with the labels that each got.

#870 854 worksite images
  client/src/Components/Pages/Profile/ProfileAnswers/ImageSlider.js
  client/src/Components/Pages/Review/Question/UploadPhoto.js
  package-lock.json
  package.json
  server/controllers/getWorksiteImgs.js
  server/middlewares/deleteFileFromServer.js
  server/middlewares/uploadFileToServer.js
  server/middlewares/uploadToGoogle.js
Labels: awaiting-review

#873 Bugfixes > 851 852 868
  client/src/Components/Pages/Admin/Organizations/OrganizationsColumns.js
  client/src/Components/Pages/Profile/HeaderSection.js
  client/src/Components/Pages/Profile/Profile.style.js
  server/controllers/admin/editOrganization.js
  server/database/dummyData/questions.js
Labels: awaiting-review

#871 849 access levels
  .vscode/launch.json
  client/src/Components/Common/Navbar/Menu.js
  client/src/Components/Common/PrivateRoute/index.js
  client/src/Components/Pages/Profile/HeaderSection.js
  client/src/Components/Pages/Profile/OverviewSection/Level0Promo.js
  client/src/Components/Pages/Profile/OverviewSection/OverallReview.js
  client/src/Components/Pages/Profile/OverviewSection/index.js
  client/src/Components/Pages/Profile/Reply.js
  client/src/Components/Pages/Profile/ReviewNotAllowedButton.js
  client/src/Components/Pages/Profile/index.js
  client/src/Components/Pages/Profile/utils.js
  client/src/helpers/index.js
  server/controllers/profile.js
  server/database/queries/reviews/index.js
Labels: awaiting-review

#875 Correct a typo (+ update text)
  client/src/Components/Common/Navbar/Navbar.style.js
  client/src/Components/Common/Navbar/index.js
  client/src/Components/Pages/Search/AddProfileSelection.js
  client/src/Components/Pages/Static/FAQ.js
  client/src/Components/Pages/UserProfile/UserReviews.js
Labels: awaiting-review

#876 Changes to columns in Admin portal
  client/src/Components/Pages/Admin/Reviews/ReviewsColumns.js
  client/src/Components/Pages/Admin/Reviews/index.js
  client/src/Components/Pages/Admin/Users/AllUsers.js
  client/src/Components/Pages/Admin/Users/UsersColumns.js
  client/src/Components/Pages/Admin/index.js
  client/src/constants/adminRoutes.js
  server/controllers/admin/getReviews.js
  server/database/queries/reviews/allReviews.js
  server/database/queries/user/allUsers.js
Labels: awaiting-review

#874 fix sticky banner overlay
  client/src/Components/Pages/Profile/Profile.style.js
Labels: awaiting-review

#846 Simon prio4 backlog chunk2
  client/src/Components/Common/Navbar/Menu.js
  client/src/Components/Pages/Signup/index.js
  client/src/Components/Pages/UploadImage/index.js
  client/src/Components/Pages/UserProfile/UserReviews.js
  server/controllers/uploadVerificationImage.js
  server/middlewares/validation.js
Labels: awaiting-review

#877 865 update profile
  client/src/Components/Common/Icon/Comment.js
  client/src/Components/Common/Icon/Flag.js
  client/src/Components/Common/Icon/Icon.js
  client/src/Components/Common/Icon/Like.js
  client/src/Components/Pages/Profile/HeaderSection.js
  client/src/Components/Pages/Profile/OverviewSection/OrganisationDetails.js
  client/src/Components/Pages/Profile/OverviewSection/OverallReview.js
  client/src/Components/Pages/Profile/OverviewSection/index.js
  client/src/Components/Pages/Profile/Profile.style.js
  client/src/Components/Pages/Profile/ProfileAnswers/CommentsBox.js
  client/src/Components/Pages/Profile/ProfileAnswers/ImageSlider.js
  client/src/Components/Pages/Profile/Reply.style.js
  client/src/Components/Pages/Profile/index.js
  client/src/theme.js
Labels: awaiting-review

#880 Design tweaks
  client/src/Components/Common/Icon/Home.js
  client/src/Components/Common/Icon/Icon.js
  client/src/Components/Common/Icon/NewWindow.js
  client/src/Components/Common/Navbar/Menu.js
  client/src/Components/Common/Navbar/index.js
  client/src/Components/Common/Select.js
  client/src/Components/Pages/Review/Question/Options/DropDown.js
  client/src/Components/Pages/Review/Question/Question.style.js
  client/src/Components/Pages/Search/AutoSuggest.js
  client/src/Components/Pages/Search/Header/index.js
  client/src/Components/Pages/UserProfile/UserReviews.js
  client/src/Components/Pages/Welcome/Welcome.style.js
  client/src/Components/Pages/Welcome/index.js
Labels: awaiting-review

#883 857 > Prevent Replies if Admin Has Replied
  client/src/Components/Pages/Profile/OverviewSection/OverallReview.js
  client/src/Components/Pages/Profile/Profile.style.js
  client/src/Components/Pages/Profile/utils.js
  server/controllers/addCommentOnReview.js
  server/database/queries/reviews/index.js
Labels: awaiting-review

#879 793 > Fix Back Browser Button & Enter Key issues
  causing
  client/src/Components/Common/GiveReview/index.js
  client/src/Components/Common/Popover/index.js
  client/src/Components/Common/Select.js
  client/src/Components/Pages/Review/Question/index.js
  client/src/Components/Pages/Review/index.js
  client/src/Components/Pages/Review/staticQuestions.js
  client/src/Components/Pages/Search/AutoSuggest.js
  client/src/Components/Pages/Signup/index.js
  client/src/Components/Pages/UploadImage/index.js
Labels: changes-requested

#882 867 > Search Updates
  client/src/Components/Common/GeneralTabs.js
  client/src/Components/Common/Icon/All.js
  client/src/Components/Common/Icon/Icon.js
  client/src/Components/Common/Icon/Recent.js
  client/src/Components/Pages/Profile/HeaderSection.js
  client/src/Components/Pages/Search/Header/Header.style.js
  client/src/Components/Pages/Search/Header/Tabs.js
  client/src/Components/Pages/Search/Header/index.js
  client/src/Components/Pages/Search/OrganisationsList.js
  client/src/Components/Pages/Search/Search.style.js
  client/src/Components/Pages/Search/index.js
Labels: changes-requested

#878 Changes to reviewing pages
  client/src/Components/Common/AntdComponents/DatePicker.js
  client/src/Components/Pages/Profile/ProfileAnswers/CanteenItemAnswer.js
  client/src/Components/Pages/Profile/ProfileAnswers/SiteItemAnswer.js
  client/src/Components/Pages/Profile/utils.js
  client/src/Components/Pages/Review/Question/Options/CheckList.js
  client/src/Components/Pages/Review/Question/Options/DateRange.js
  client/src/Components/Pages/Review/Question/Options/Number.js
  client/src/Components/Pages/Review/Question/Options/YesNo.js
  client/src/Components/Pages/Review/Question/Options/YesNoOption.js
  client/src/Components/Pages/Review/Question/index.js
  client/src/Components/Pages/Review/index.js
  client/src/Components/Pages/Review/staticQuestions.js
  client/src/Components/Pages/Signup/index.js
  client/src/Components/Pages/UploadImage/index.js
  server/controllers/review.js
  server/database/dummyData/questions.js
Labels: awaiting-review

#884 866 your profile updates
  client/src/Components/Pages/UserProfile/UserPoints.js
  client/src/Components/Pages/UserProfile/UserPoints.style.js
  client/src/Components/Pages/UserProfile/UserProfile.style.js
  client/src/Components/Pages/UserProfile/UserReviews.js
  client/src/Components/Pages/UserProfile/index.js
  client/src/Components/index.js
  client/src/constants/naviagationUrls.js
Labels: changes-requested

#891 fix reloading search page
  client/src/Components/Common/GeneralTabs.js
  client/src/Components/Pages/Profile/HeaderSection.js
  client/src/Components/Pages/Search/Header/Tabs.js
  client/src/Components/Pages/Search/Header/index.js
  client/src/Components/Pages/Search/index.js
Labels: awaiting-review

#892 show prompt when modals are opened
  client/package-lock.json
  client/package.json
  client/src/Components/Common/Select.js
  client/src/Components/Pages/EditProfile/EditProfileSection.js
  client/src/Components/Pages/Review/Question/Options/DropDown.js
  client/src/Components/Pages/Review/index.js
  client/src/Components/Pages/Signup/index.js
  client/src/Components/Pages/UploadImage/index.js
Labels: awaiting-review

#886 sign up tweaks
  client/src/Components/Common/AddOrganisationPages.style.js
  client/src/Components/Common/Navbar/Menu.js
  client/src/Components/Pages/AddProfileAfterSignUp/index.js
  client/src/Components/Pages/AddProfileReviewStart/index.js
  client/src/Components/Pages/AddProfileSelection/index.js
  client/src/Components/Pages/Login/index.js
  client/src/Components/Pages/Profile/OverviewSection/OverallReview.js
  client/src/Components/Pages/Profile/ReviewNotAllowedButton.js
  client/src/Components/Pages/Review/index.js
  client/src/Components/Pages/Search/AddProfileReviewStart.js
  client/src/Components/Pages/Search/AutoSuggest.js
  client/src/Components/Pages/Search/Search.style.js
  client/src/Components/Pages/Signup/index.js
  client/src/Components/Pages/UploadImage/index.js
  client/src/Components/Pages/UserProfile/UserReviews.js
  client/src/Components/Pages/VerificationRequired/index.js
  client/src/Components/index.js
  client/src/constants/naviagationUrls.js
  server/controllers/admin/deleteUser.js
  server/controllers/admin/rejectUser.js
  server/controllers/organization/index.js
  server/controllers/organization/organization.controller.js
  server/controllers/organization/organization.service.js
  server/controllers/organizations.js
  server/controllers/review.js
  server/database/models/Organization.js
  server/database/queries/organizations/addOrganization.js
  server/database/queries/user/index.js
  server/router/index.js
Labels: awaiting-review, changes-requested

#881 update signup pages
  client/src/Components/Common/CancelLink.js
  client/src/Components/Common/Formik/Formik.style.js
  client/src/Components/Common/Logo.js
  client/src/Components/Pages/Signup/index.js
  client/src/Components/Pages/UploadImage/index.js
  server/middlewares/validation.js
Labels: awaiting-review

#893 style changes
  client/src/Components/Common/Navbar/Navbar.style.js
  client/src/Components/Pages/Review/Question/Options/DateRange.js
  client/src/Components/Pages/Review/Question/Options/Number.js
  client/src/Components/Pages/Review/Question/Question.style.js
Labels: awaiting-review

#906 Show hidden question + delete text
  client/src/Components/Pages/Review/validationSchema.js
  client/src/Components/Pages/Signup/index.js
  client/src/Components/Pages/UploadImage/index.js
  server/database/dummyData/questions.js
Labels: awaiting-review

#907 fix edit reviews access level
  causing
  server/router/index.js
  {
Labels: awaiting-review

#910 access levels
  client/src/Components/Common/Navbar/Menu.js
  client/src/Components/Common/Navbar/index.js
  client/src/Components/Common/PrivateRoute/index.js
  client/src/Components/Pages/UserProfile/index.js
  client/src/Components/index.js
Labels: awaiting-review

#913 disable prompt when user is awaiting/verified
  client/src/Components/Pages/UploadImage/index.js
Labels: awaiting-review

#914 PreReview bug
  client/src/Components/Pages/PreReview/PreReview.style.js
  client/src/Components/Pages/PreReview/index.js
  server/controllers/review.js
  server/router/index.js
Labels: awaiting-review

#917 disable orgs to be auto selected for non worker users
  client/src/Components/Pages/Signup/index.js
Labels: awaiting-review

#919 disable report content link for un-logged in users
  client/src/Components/Pages/Profile/OverviewSection/OverallReview.js
Labels: awaiting-review

#920 hide the contractor list if there is no more one
  client/src/Components/Common/Button.js
  client/src/Components/Pages/Profile/HeaderSection.js
  client/src/Components/Pages/Profile/OverviewSection/ContractorsList.js
Labels: awaiting-review

#915 fix redirection for not-worker after sign-up
  client/src/Components/Pages/Profile/HeaderSection.js
  client/src/Components/Pages/Signup/index.js
  client/src/Components/Pages/UploadImage/index.js
  client/src/Components/Pages/UserProfile/index.js
  server/controllers/uploadVerificationImage.js
Labels: awaiting-review

#921 Minor bug fixes
  client/src/Components/Common/Navbar/index.js
  client/src/Components/Pages/Profile/HeaderSection.js
  client/src/Components/Pages/Profile/ProfileAnswers/YesNoAnswer.js
Labels: awaiting-review

#947 Render the missing items in the menu
  client/src/Components/Common/Navbar/index.js
Labels: awaiting-review

#948 sort organisations alphabetically
  client/src/Components/Pages/Review/Question/Options/DropDown.js
  client/src/helpers/index.js
Labels: awaiting-review

#949 update suggestion link
  client/src/Components/Pages/Search/AutoSuggest.js
Labels: awaiting-review

#954 checks if storeOrg is instanceof Function
  client/src/Components/Pages/Search/OrganisationRow.js
Labels: awaiting-review

#952 changed reviews by workers count to be written or audio reviews
  client/src/Components/Pages/Profile/OverviewSection/OverallReview.js
Labels: awaiting-review

#951 create virtualized select component
  client/package-lock.json
  client/package.json
  client/src/Components/Common/ReactSelect.js
  client/src/Components/Common/Select.js
  client/src/Components/Common/withSelect.js
  client/src/Components/Pages/Review/Question/Options/DropDown.js
  client/src/Components/Pages/Review/index.js
Labels: awaiting-review

#955 931 make welcome page landing page
  client/src/Components/Common/Navbar/Menu.js
  client/src/Components/Common/Navbar/index.js
  client/src/Components/Pages/Intro/index.js
  client/src/Components/Pages/Landing/index.js
  client/src/Components/Pages/Login/index.js
  client/src/Components/Pages/OrgCheck/index.js
  client/src/Components/Pages/Signup/index.js
  client/src/Components/Pages/UserProfile/UserReviews.js
  client/src/Components/index.js
  client/src/constants/naviagationUrls.js
Labels: awaiting-review

#956 Remove unsupported resize observer
  client/src/Components/Pages/Admin/Admin.style.js
  client/src/Components/Pages/Admin/SideMenu/SideMenu.style.js
  client/src/Components/Pages/Admin/SideMenu/index.js
  client/src/Components/Pages/Admin/index.js
Labels: awaiting-review

#959 design update data bars and profile section layout
  client/src/Components/Common/Icon/AmountExpected.js
  client/src/Components/Common/Icon/Contract.js
  client/src/Components/Common/Icon/ContractBefore.js
  client/src/Components/Common/Icon/CorrectHours.js
  client/src/Components/Common/Icon/CorrectRate.js
  client/src/Components/Common/Icon/CorrectWork.js
  client/src/Components/Common/Icon/GetAround.js
  client/src/Components/Common/Icon/Icon.js
  client/src/Components/Common/Icon/Materials.js
  client/src/Components/Common/Icon/OtherEmployees.js
  client/src/Components/Common/Icon/Overall.js
  client/src/Components/Common/Icon/PaidOnTime.js
  client/src/Components/Common/Icon/PayslipsAccessible.js
  client/src/Components/Common/Icon/PayslipsInfo.js
  client/src/Components/Common/Icon/Respect.js
  client/src/Components/Common/Icon/SafeSite.js
  client/src/Components/Common/Icon/SafetySeriously.js
  client/src/Components/Common/Icon/SecureTools.js
  client/src/Components/Common/Icon/SharedInfo.js
  client/src/Components/Common/Icon/TidySite.js
  client/src/Components/Common/Icon/TimesheetCharge.js
  client/src/Components/Common/Icon/ToiletsClean.js
  client/src/Components/Pages/Profile/DetailedSection/DetailedAnswers.js
  client/src/Components/Pages/Profile/DetailedSection/ReviewSection.js
  client/src/Components/Pages/Profile/DetailedSection/ReviewSection.style.js
  client/src/Components/Pages/Profile/OverviewSection/OverallReview.js
  client/src/Components/Pages/Profile/ProfileAnswers/ProfileAnswers.style.js
  client/src/Components/Pages/Profile/ProfileAnswers/YesNoAnswer.js
  client/src/theme.js
  server/database/dummyData/questions.js
Labels: awaiting-review
